/**
 * Cloudflare Worker for FlecBlog Installer
 * 提供原生部署安装脚本的动态分发服务
 *
 * 访问地址:
 * - https://install.talen.cyou/         -> 返回安装脚本
 *
 * 部署: wrangler deploy install.js --name flec-install
 */

const REPO = "talen8/FlecBlogTest";

export default {
  async fetch(request) {
    const url = new URL(request.url);

    if (url.pathname !== "/" && url.pathname !== "") {
      return new Response("Not Found", { status: 404 });
    }

    return new Response(getUnifiedScript(), {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  },
};

function getUnifiedScript() {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# FlecBlog 一键安装脚本",
    "# 用法: curl -fsSL https://install.talen.cyou | bash",
    "",
    'REPO="' + REPO + '"',
    'INSTALL_DIR="${FLECBLOG_DIR:-/opt/flecblog}"',
    "",
    "RED='\\033[0;31m'",
    "GREEN='\\033[0;32m'",
    "YELLOW='\\033[1;33m'",
    "NC='\\033[0m'",
    "",
    'info()  { echo -e "${GREEN}[INFO]${NC} $*"; }',
    'warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }',
    'error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }',
    "",
    '# ===================================================================',
    '#  通用函数',
    '# ===================================================================',
    "",
"get_server_ip() {",
  '  local ip=""',
  '  for svc in "https://icanhazip.com" "https://ipinfo.io/ip" "https://checkip.amazonaws.com"; do',
  '    ip=$(curl -fsSL --connect-timeout 5 "$svc" 2>/dev/null) && break',
  "  done",
  '  echo "${ip:-localhost}"',
  "}",
  "",
  "detect_system() {",
  '  OS="$(uname -s)"',
  '  ARCH="$(uname -m)"',
    '  case "$OS" in',
    "    Linux*)  OS=\"linux\";;",
    "    Darwin*) OS=\"darwin\";;",
    '    *)       error "不支持的操作系统: $OS";;',
    "  esac",
    '  case "$ARCH" in',
    "    x86_64)  ARCH=\"amd64\";;",
    "    aarch64) ARCH=\"arm64\";;",
    "    arm64)   ARCH=\"arm64\";;",
    '    *)       error "不支持的架构: $ARCH";;',
    "  esac",
    '  info "检测到系统: ${OS}/${ARCH}"',
    "}",
    "",
    "check_deps() {",
    "  if ! command -v node &>/dev/null; then",
    '    warn "未检测到 Node.js，正在安装..."',
    "    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - 2>/dev/null || true",
    "    apt-get install -y nodejs 2>/dev/null || {",
    '      error "自动安装 Node.js 失败，请手动安装 Node.js 22+"',
    "    }",
    "  fi",
    "  NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)",
    '  [ "$NODE_VER" -ge 22 ] || error "需要 Node.js 22+，当前版本: $(node -v)"',
    '  info "Node.js: $(node -v)"',
    "",
    "  if ! command -v pm2 &>/dev/null; then",
    '    info "正在安装 PM2..."',
    "    npm install -g pm2",
    "  fi",
    '  info "PM2: $(pm2 -v)"',
    "}",
    "",
    "get_latest_version() {",
    '  VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | grep \'"tag_name"\' | sed \'s/.*"v\\(.*\\)".*/\\1/\' 2>/dev/null || echo "")',
    '  if [ -z "$VERSION" ]; then',
    '    error "无法获取最新版本，请检查网络连接"',
    "  fi",
    '  info "最新版本: v${VERSION}"',
    "}",
    "",
    "install_binary() {",
    '  local platform="${OS}_${ARCH}"',
    '  local filename="flec-server_${platform}.tar.gz"',
    "",
    "  local mirrors=(",
    '    "https://ghfast.top/https://github.com"',
    '    "https://ghproxy.net/https://github.com"',
    '    "https://github.com"',
    "  )",
    "",
    '  info "正在下载 Server 二进制..."',
    '  mkdir -p "${INSTALL_DIR}"',
    "",
    "  local downloaded=false",
    '  for mirror in "${mirrors[@]}"; do',
    '    [ -z "$mirror" ] && continue',
    '    local url="${mirror}/${REPO}/releases/download/v${VERSION}/${filename}"',
    '    echo "  尝试: $mirror"',
    '    if curl -fSL --connect-timeout 10 --max-time 300 --progress-bar -o "${INSTALL_DIR}/${filename}" "$url"; then',
    "      downloaded=true",
    "      break",
    "    fi",
    '    echo "  失败，尝试下一个..."',
    "  done",
    "",
    '  if [ "$downloaded" != "true" ]; then',
    '    error "所有镜像下载失败"',
    "  fi",
    "",
    "  local THEME_BACKUP=\"\"",
    '  if [ -d "${INSTALL_DIR}/blog/themes" ]; then',
    '    THEME_BACKUP="$(mktemp -d)"',
    '    for theme_dir in "${INSTALL_DIR}/blog/themes"/*/; do',
    '      [ -d "$theme_dir" ] || continue',
    '      theme_name=$(basename "$theme_dir")',
    '      if [ "$theme_name" != "default" ]; then',
    '        cp -r "$theme_dir" "${THEME_BACKUP}/${theme_name}"',
    "      fi",
    "    done",
    "  fi",
    "",
    '  tar xzf "${INSTALL_DIR}/${filename}" -C "${INSTALL_DIR}" --strip-components=1',
    '  rm -f "${INSTALL_DIR}/${filename}"',
    '  rm -rf "${INSTALL_DIR}/blog/.output" "${INSTALL_DIR}/blog/.nuxt" 2>/dev/null || true',
    "",
    '  if [ -n "$THEME_BACKUP" ] && [ -d "$THEME_BACKUP" ]; then',
    '    for theme_dir in "${THEME_BACKUP}"/*/; do',
    '      [ -d "$theme_dir" ] || continue',
    '      theme_name=$(basename "$theme_dir")',
    '      cp -r "$theme_dir" "${INSTALL_DIR}/blog/themes/${theme_name}"',
    "    done",
    '    rm -rf "$THEME_BACKUP"',
    "  fi",
    "",
    '  if [ ! -f "${INSTALL_DIR}/flec-server" ]; then',
    '    error "下载失败，请检查网络或手动下载"',
    "  fi",
    '  chmod +x "${INSTALL_DIR}/flec-server"',
    '  info "Server 二进制已安装到 ${INSTALL_DIR}/flec-server"',
    "}",
    "",
    "install_blog() {",
    '  if [ ! -d "${INSTALL_DIR}/blog" ]; then',
    '    error "未找到 Blog 源码，请确认 Server 包已正确解压"',
    "  fi",
    "",
    '  if [ -d "${INSTALL_DIR}/blog/.output" ]; then',
    '    info "Blog 已构建，跳过"',
    "    return",
    "  fi",
    "",
    '  local has_swap=false',
    '  if swapon --show 2>/dev/null | grep -q .; then',
    '    has_swap=true',
    "  fi",
    '  if [ "$has_swap" != "true" ]; then',
    '    info "未检测到 swap，创建临时 2GB swap..."',
    "    fallocate -l 2G /tmp/flecblog.swap 2>/dev/null || dd if=/dev/zero of=/tmp/flecblog.swap bs=1M count=2048 2>/dev/null",
    "    chmod 600 /tmp/flecblog.swap",
    "    mkswap /tmp/flecblog.swap 2>/dev/null",
    "    swapon /tmp/flecblog.swap 2>/dev/null || true",
    "  fi",
    "",
    '  info "正在安装 Blog 依赖..."',
    '  cd "${INSTALL_DIR}/blog"',
    "  NODE_ENV=production NUXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=\"--max-old-space-size=3072\" npm ci --registry=https://registry.npmmirror.com",
    '  info "正在构建 Blog..."',
    "  NUXT_TELEMETRY_DISABLED=1 NUXT_PUBLIC_ACTIVE_THEME=default NODE_OPTIONS=\"--max-old-space-size=3072\" npm run build",
    '  cd "${INSTALL_DIR}"',
    "",
    '  if [ "$has_swap" != "true" ] && [ -f /tmp/flecblog.swap ]; then',
    "    swapoff /tmp/flecblog.swap 2>/dev/null || true",
    "    rm -f /tmp/flecblog.swap",
    "  fi",
    "}",
    "",
    "setup_config() {",
    '  local env_file="${INSTALL_DIR}/.env"',
    "",
    "",
    '  if [ ! -f "${INSTALL_DIR}/ecosystem.config.js" ]; then',
    '    cat > "${INSTALL_DIR}/ecosystem.config.js" << \'PM2EOF\'',
    "module.exports = {",
    "  apps: [",
    "    {",
    '      name: "flec-server",',
    '      script: "./flec-server",',
    '      env_file: "./.env",',
    '      env: { NODE_ENV: "production" },',
    '      max_memory_restart: "512M",',
    "      exp_backoff_restart_delay: 100,",
    "    },",
    "    {",
    '      name: "flec-blog",',
    '      script: "./blog/.output/server/index.mjs",',
    '      env_file: "./.env",',
    "      env: {",
    '        NODE_ENV: "production",',
    '        NUXT_PUBLIC_API_URL: "http://localhost:8080/api/v1",',
    "      },",
    '      max_memory_restart: "512M",',
    "      exp_backoff_restart_delay: 100,",
    "    },",
    "  ],",
    "};",
    "PM2EOF",
    "  fi",
    "}",
    "",
    "start_services() {",
    '  info "正在启动服务..."',
    '  cd "${INSTALL_DIR}"',
    "  pm2 delete all 2>/dev/null || true",
    "  pm2 start ecosystem.config.js",
    "  pm2 save",
    "  pm2 startup 2>/dev/null || true",
    '  info "服务已启动"',
    "}",
    "",
'print_install_result() {',
  '  local server_ip=$(get_server_ip)',
  '  echo ""',
  '  echo -e "${GREEN}========================================${NC}"',
  '  echo -e "${GREEN}  FlecBlog 安装完成!${NC}"',
  '  echo -e "${GREEN}========================================${NC}"',
  '  echo ""',
  '  echo -e "  安装目录: ${INSTALL_DIR}"',
  '  echo -e "  Blog 已构建，服务已启动"',
  '  echo ""',
  '  echo -e "  ${YELLOW}首次使用请访问以下地址完成数据库配置:${NC}"',
  '  echo -e "  ${GREEN}http://${server_ip}:8080/setup/${NC}"',
  '  echo ""',
  '  echo -e "  配置完成后服务将自动重启"',
  '  echo ""',
  "}",
    "",
    '# ===================================================================',
    '#  安装流程',
    '# ===================================================================',
    "",
    "install_main() {",
    "  detect_system",
    "  check_deps",
    "  get_latest_version",
    "  install_binary",
    "  install_blog",
    "  setup_config",
    "  start_services",
    "  print_install_result",
    "}",
    "",
    '# ===================================================================',
    '#  主入口',
    '# ===================================================================',
    "",
    "main() {",
    "  install_main",
    "}",
    "",
    "main",
  ];

  return lines.join("\n");
}
