/**
 * Cloudflare Worker for FlecBlog Installer
 * 提供原生部署安装脚本的动态分发服务
 *
 * 访问地址:
 * - https://install.talen.cyou/         -> 返回安装脚本
 *
 * 部署: wrangler deploy install.js --name flec-install
 */

const REPO = "talen8/FlecBlogTest";

export default {
  async fetch(request) {
    const url = new URL(request.url);

    if (url.pathname !== "/" && url.pathname !== "") {
      return new Response("Not Found", { status: 404 });
    }

    return new Response(getUnifiedScript(), {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  },
};

function getUnifiedScript() {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# FlecBlog 一键安装脚本",
    "# 用法: curl -fsSL https://install.talen.cyou | bash",
    "",
    'REPO="' + REPO + '"',
    'INSTALL_DIR="${FLECBLOG_DIR:-/opt/flecblog}"',
    'DEPLOY_MODE=""',
    'DB_HOST=""',
    'DB_PORT=5432',
    'DB_NAME="postgres"',
    'DB_USER="postgres"',
    'DB_PASSWORD=""',
    'JWT_SECRET=""',
    "SERVER_PORT=8080",
    "BLOG_PORT=3000",
    "",
    "RED='\\033[0;31m'",
    "GREEN='\\033[0;32m'",
    "YELLOW='\\033[1;33m'",
    "BLUE='\\033[0;34m'",
    "NC='\\033[0m'",
    "",
    'info()  { echo -e "${GREEN}[INFO]${NC} $*"; }',
    'warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }',
    'error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }',
    'step()  { echo -e "${BLUE}==>${NC} $*"; }',
    "",
    '# ===================================================================',
    '#  通用函数',
    '# ===================================================================',
    "",
    "get_server_ip() {",
    '  local ip=""',
    '  for svc in "https://icanhazip.com" "https://ipinfo.io/ip" "https://checkip.amazonaws.com"; do',
    '    ip=$(curl -fsSL --connect-timeout 5 "$svc" 2>/dev/null) && break',
    "  done",
    '  echo "${ip:-localhost}"',
    "}",
    "",
    "detect_system() {",
    '  OS="$(uname -s)"',
    '  ARCH="$(uname -m)"',
    '  case "$OS" in',
    "    Linux*)  OS=\"linux\";;",
    "    Darwin*) OS=\"darwin\";;",
    '    *)       error "不支持的操作系统: $OS";;',
    "  esac",
    '  case "$ARCH" in',
    "    x86_64)  ARCH=\"amd64\";;",
    "    aarch64) ARCH=\"arm64\";;",
    "    arm64)   ARCH=\"arm64\";;",
    '    *)       error "不支持的架构: $ARCH";;',
    "  esac",
    '  info "检测到系统: ${OS}/${ARCH}"',
    "}",
    "",
    "check_deps() {",
    "  if ! command -v node &>/dev/null; then",
    '    warn "未检测到 Node.js，正在安装..."',
    "    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - 2>/dev/null || true",
    "    apt-get install -y nodejs 2>/dev/null || {",
    '      error "自动安装 Node.js 失败，请手动安装 Node.js 22+"',
    "    }",
    "  fi",
    "  NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)",
    '  [ "$NODE_VER" -ge 22 ] || error "需要 Node.js 22+，当前版本: $(node -v)"',
    '  info "Node.js: $(node -v)"',
    "",
    "  if ! command -v pm2 &>/dev/null; then",
    '    info "正在安装 PM2..."',
    "    npm install -g pm2",
    "  fi",
    '  info "PM2: $(pm2 -v)"',
    "}",
    "",
    "get_latest_version() {",
    '  VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | grep \'"tag_name"\' | sed \'s/.*"v\\(.*\\)".*/\\1/\' 2>/dev/null || echo "")',
    '  if [ -z "$VERSION" ]; then',
    '    error "无法获取最新版本，请检查网络连接"',
    "  fi",
    '  info "最新版本: v${VERSION}"',
    "}",
    "",
    '# ===================================================================',
    '#  模式选择',
    '# ===================================================================',
    "",
    "show_mode_selection() {",
    '  echo ""',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo -e "${GREEN}  FlecBlog 安装向导${NC}"',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo ""',
    '  echo "请选择部署模式："',
    '  echo "  1) 全新安装（首次部署，需配置数据库）"',
    '  echo "  2) 从 Docker Compose 迁移"',
    '  echo "  3) 从 flecb 迁移"',
    '  echo "  4) 手动迁移（仅显示指南）"',
    '  echo ""',
    '  while true; do',
    '    read -rp "请输入选项 [1-4]: " mode_choice',
    '    case "$mode_choice" in',
    '      1) DEPLOY_MODE="fresh"; break;;',
    '      2) DEPLOY_MODE="docker"; break;;',
    '      3) DEPLOY_MODE="flecb"; break;;',
    '      4) DEPLOY_MODE="manual"; break;;',
    '      *) warn "无效选项，请重新输入";;',
    "    esac",
    "  done",
    "}",
    "",
    '# ===================================================================',
    '#  模式 1：全新安装',
    '# ===================================================================',
    "",
    "ask_database_config() {",
    '  step "配置数据库连接"',
    '  echo ""',
    "",
    '  while true; do',
    '    read -rp "  数据库主机 (默认 localhost): " input_host',
    '    DB_HOST="${input_host:-localhost}"',
    "",
    '    read -rp "  数据库端口 (默认 5432): " input_port',
    '    DB_PORT="${input_port:-5432}"',
    "",
    '    read -rp "  数据库名称 (默认 postgres): " input_name',
    '    DB_NAME="${input_name:-postgres}"',
    "",
    '    read -rp "  数据库用户 (默认 postgres): " input_user',
    '    DB_USER="${input_user:-postgres}"',
    "",
    '    read -rsp "  数据库密码: " input_password',
    '    echo ""',
    '    DB_PASSWORD="$input_password"',
    "",
    '    if [ -z "$DB_PASSWORD" ]; then',
    '      warn "数据库密码不能为空"',
    "      continue",
    "    fi",
    "",
    '    info "正在测试数据库连接..."',
    '    if PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "\\q" 2>/dev/null; then',
    '      info "数据库连接成功"',
    "      break",
    "    else",
    '      warn "数据库连接失败，请检查配置并重试"',
    '      echo ""',
    "    fi",
    "  done",
    "}",
    "",
    "ask_jwt_secret() {",
    '  step "配置 JWT 密钥"',
    '  echo ""',
    '  read -rp "  请输入 JWT 密钥 (回车自动生成): " input_jwt',
    "",
    '  if [ -z "$input_jwt" ]; then',
    '    JWT_SECRET=$(openssl rand -base64 32)',
    '    info "已自动生成 JWT 密钥"',
    "  else",
    '    JWT_SECRET="$input_jwt"',
    "  fi",
    "}",
    "",
    "ask_ports() {",
    '  step "配置服务端口"',
    '  echo ""',
    "",
    '  while true; do',
    '    read -rp "  Server 端口 (默认 8080): " input_server_port',
    '    SERVER_PORT="${input_server_port:-8080}"',
    '    if ! command -v ss &>/dev/null; then break; fi',
    '    if ss -tlnp 2>/dev/null | grep -qE "[:.]${SERVER_PORT}[[:space:]]"; then',
    '      local proc=$(ss -tlnp 2>/dev/null | grep "[:.]${SERVER_PORT}[[:space:]]" | head -1 | sed "s/.*users:((\\\"\\([^\\\"]*\\)\\\".*/\\1/")',
    '      warn "端口 ${SERVER_PORT} 已被占用 (进程: ${proc:-未知})，请更换"',
    "    else",
    "      break",
    "    fi",
    "  done",
    "",
    '  while true; do',
    '    read -rp "  Blog 端口 (默认 3000): " input_blog_port',
    '    BLOG_PORT="${input_blog_port:-3000}"',
    '    if ! command -v ss &>/dev/null; then break; fi',
    '    if ss -tlnp 2>/dev/null | grep -qE "[:.]${BLOG_PORT}[[:space:]]"; then',
    '      local proc=$(ss -tlnp 2>/dev/null | grep "[:.]${BLOG_PORT}[[:space:]]" | head -1 | sed "s/.*users:((\\\"\\([^\\\"]*\\)\\\".*/\\1/")',
    '      warn "端口 ${BLOG_PORT} 已被占用 (进程: ${proc:-未知})，请更换"',
    "    else",
    "      break",
    "    fi",
    "  done",
    "}",
    "",
    "confirm_config() {",
    '  echo ""',
    '  step "请确认配置信息"',
    '  echo ""',
    '  echo "  数据库主机: ${DB_HOST}"',
    '  echo "  数据库端口: ${DB_PORT}"',
    '  echo "  数据库名称: ${DB_NAME}"',
    '  echo "  数据库用户: ${DB_USER}"',
    '  echo "  JWT 密钥: ${JWT_SECRET:0:16}..."',
    '  echo "  Server 端口: ${SERVER_PORT}"',
    '  echo "  Blog 端口: ${BLOG_PORT}"',
    '  echo ""',
    '  read -rp "确认无误？[Y/n] " confirm',
    '  if [ "$confirm" = "n" ] || [ "$confirm" = "N" ]; then',
    '    error "已取消安装"',
    "  fi",
    "}",
    "",
    "mode_fresh_install() {",
    '  info "开始全新安装流程"',
    '  echo ""',
    "",
    "  ask_database_config",
    "  ask_jwt_secret",
    "  ask_ports",
    "  confirm_config",
    "",
    "  install_binary",
    "  install_blog",
    "  write_env_and_ecosystem",
    "  start_services",
    "  print_install_result",
    "}",
    "",
    '# ===================================================================',
    '#  模式 2：Docker 迁移',
    '# ===================================================================',
    "",
    "ask_compose_path() {",
    '  step "配置 Docker Compose 路径"',
    '  echo ""',
    "",
    '  while true; do',
    '    read -rp "  docker-compose.yml 所在目录路径: " compose_dir',
    '    if [ -z "$compose_dir" ]; then',
    '      warn "路径不能为空"',
    "      continue",
    "    fi",
    "",
    '    if [ ! -f "${compose_dir}/docker-compose.yml" ]; then',
    '      warn "未找到 ${compose_dir}/docker-compose.yml"',
    "      continue",
    "    fi",
    "",
    '    COMPOSE_DIR="$compose_dir"',
    "    break",
    "  done",
    "}",
    "",
    "parse_env_file() {",
    '  local env_file="${COMPOSE_DIR}/.env"',
    '  if [ ! -f "$env_file" ]; then',
    '    warn "未找到 ${env_file}，将使用默认配置"',
    "    return",
    "  fi",
    "",
    '  DB_PASSWORD=$(grep "^DB_PASSWORD=" "$env_file" 2>/dev/null | cut -d= -f2- || echo "")',
    '  JWT_SECRET=$(grep "^JWT_SECRET=" "$env_file" 2>/dev/null | cut -d= -f2- || echo "")',
    '  local api_url=$(grep "^API_URL=" "$env_file" 2>/dev/null | cut -d= -f2- || echo "")',
    "",
    '  if [ -n "$api_url" ]; then',
    '    SERVER_PORT=$(echo "$api_url" | sed \'s/.*:\\([0-9]*\\).*/\\1/\' || echo "8080")',
    "  fi",
    "",
    '  info "已从 .env 读取配置"',
    "}",
    "",
    "ask_volume_path() {",
    '  step "配置数据卷路径"',
    '  echo ""',
    '  read -rp "  Docker 数据卷路径 (默认 /srv/flecblog): " input_volume',
    '  VOLUME_PATH="${input_volume:-/srv/flecblog}"',
    "",
    '  if [ ! -d "$VOLUME_PATH" ]; then',
    '    warn "目录 ${VOLUME_PATH} 不存在"',
    '    read -rp "  继续？[y/N] " confirm_volume',
    '    if [ "$confirm_volume" != "y" ] && [ "$confirm_volume" != "Y" ]; then',
    '      error "已取消迁移"',
    "    fi",
    "  fi",
    "}",
    "",
    "ask_container_name() {",
    '  step "配置容器名称"',
    '  echo ""',
    '  read -rp "  PostgreSQL 容器名 (默认 flec_postgres): " input_container',
    '  CONTAINER_NAME="${input_container:-flec_postgres}"',
    "}",
    "",
    "confirm_migration_plan() {",
    '  echo ""',
    '  step "请确认迁移计划"',
    '  echo ""',
    '  echo "  备份目录: /tmp/flecblog-backup"',
    '  echo "  Compose 目录: ${COMPOSE_DIR}"',
    '  echo "  数据卷路径: ${VOLUME_PATH}"',
    '  echo "  数据库容器: ${CONTAINER_NAME}"',
    '  echo "  Server 端口: ${SERVER_PORT}"',
    '  echo "  Blog 端口: ${BLOG_PORT}"',
    '  echo ""',
    '  read -rp "确认开始迁移？[Y/n] " confirm',
    '  if [ "$confirm" = "n" ] || [ "$confirm" = "N" ]; then',
    '    error "已取消迁移"',
    "  fi",
    "}",
    "",
    "backup_docker_data() {",
    '  step "备份 Docker 数据"',
    "  mkdir -p /tmp/flecblog-backup",
    "",
    '  if [ -f "${COMPOSE_DIR}/.env" ]; then',
    '    cp "${COMPOSE_DIR}/.env" /tmp/flecblog-backup/.env',
    '    info "已备份 .env"',
    "  fi",
    "",
    '  if [ -d "$VOLUME_PATH" ]; then',
    '    cp -r "$VOLUME_PATH" /tmp/flecblog-backup/',
    '    info "已备份数据卷"',
    "  fi",
    "",
    '  if docker ps -a --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then',
    '    docker exec "$CONTAINER_NAME" pg_dump -U postgres -d postgres > /tmp/flecblog-backup/flecblog.sql 2>/dev/null || {',
    '      warn "数据库备份失败，继续执行..."',
    "    }",
    '    info "已备份数据库"',
    "  fi",
    "}",
    "",
    "stop_docker() {",
    '  step "停止 Docker 服务"',
    '  cd "$COMPOSE_DIR" && docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true',
    '  info "Docker 服务已停止"',
    "}",
    "",
    "copy_data() {",
    '  step "迁移数据到安装目录"',
    "",
    '  if [ -f "${COMPOSE_DIR}/.env" ]; then',
    '    cp "${COMPOSE_DIR}/.env" "${INSTALL_DIR}/.env"',
    '    sed -i "s/DB_HOST=postgres/DB_HOST=localhost/" "${INSTALL_DIR}/.env"',
    '    info "已复制并修正 .env"',
    "  fi",
    "",
    '  if [ -d "${VOLUME_PATH}/uploads" ]; then',
    '    mkdir -p "${INSTALL_DIR}/uploads"',
    '    cp -r "${VOLUME_PATH}/uploads"/* "${INSTALL_DIR}/uploads/" 2>/dev/null || true',
    '    info "已复制上传文件"',
    "  fi",
    "}",
    "",
    "ask_postgres_deployment() {",
    '  step "PostgreSQL 部署方式"',
    '  echo ""',
    '  echo "请选择 PostgreSQL 部署方式："',
    '  echo "  1) 宿主机原生安装（推荐）"',
    '  echo "  2) Docker 单独运行"',
    '  echo "  3) 手动配置（跳过）"',
    '  echo ""',
    "",
    '  while true; do',
    '    read -rp "请输入选项 [1-3]: " pg_choice',
    '    case "$pg_choice" in',
    "      1)",
    '        echo ""',
    '        echo "请执行以下命令安装 PostgreSQL："',
    '        echo "  sudo apt update && sudo apt install -y postgresql postgresql-contrib"',
    '        echo "  sudo systemctl enable --now postgresql"',
    '        echo ""',
    '        echo "导入备份数据："',
    '        echo "  sudo -u postgres psql -d postgres < /tmp/flecblog-backup/flecblog.sql"',
    '        echo ""',
    '        read -rp "完成后按回车继续..."',
    "        break",
    "        ;;",
    "      2)",
    '        echo ""',
    '        echo "请执行以下命令运行 PostgreSQL 容器："',
    '        echo "  docker run -d \\\\"',
    '        echo "    --name flec_postgres \\\\"',
    '        echo "    --restart unless-stopped \\\\"',
    '        echo "    -e POSTGRES_DB=postgres \\\\"',
    '        echo "    -e POSTGRES_USER=postgres \\\\"',
    '        echo "    -e POSTGRES_PASSWORD=${DB_PASSWORD} \\\\"',
    '        echo "    -p 5432:5432 \\\\"',
    '        echo "    -v postgres_data:/var/lib/postgresql/data \\\\"',
    '        echo "    postgres:15-alpine"',
    '        echo ""',
    '        echo "导入备份数据："',
    '        echo "  docker exec -i flec_postgres psql -U postgres -d postgres < /tmp/flecblog-backup/flecblog.sql"',
    '        echo ""',
    '        read -rp "完成后按回车继续..."',
    "        break",
    "        ;;",
    "      3)",
    '        info "跳过 PostgreSQL 配置，请手动完成"',
    "        break",
    "        ;;",
    "      *)",
    '        warn "无效选项，请重新输入"',
    "        ;;",
    "    esac",
    "  done",
    "}",
    "",
    "mode_docker_migration() {",
    '  info "开始 Docker 迁移流程"',
    '  echo ""',
    "",
    "  ask_compose_path",
    "  parse_env_file",
    "  ask_volume_path",
    "  ask_container_name",
    "  ask_ports",
    "  confirm_migration_plan",
    "",
    "  backup_docker_data",
    "  stop_docker",
    "",
    "  install_binary",
    "  install_blog",
    "  copy_data",
    "",
    "  ask_postgres_deployment",
    "",
    "  write_env_and_ecosystem",
    "  start_services",
    "  print_install_result",
    "}",
    "",
    '# ===================================================================',
    '#  模式 3：flecb 迁移',
    '# ===================================================================',
    "",
    "uninstall_flecb() {",
    '  if command -v flecb &>/dev/null; then',
    '    step "卸载 flecb"',
    '    flecb uninstall 2>/dev/null || warn "flecb 卸载失败，请手动执行"',
    '    info "flecb 已卸载"',
    "  fi",
    "}",
    "",
    "mode_flecb_migration() {",
    '  info "开始 flecb 迁移流程"',
    '  echo ""',
    "",
    "  mode_docker_migration",
    "  uninstall_flecb",
    "}",
    "",
    '# ===================================================================',
    '#  模式 4：手动迁移',
    '# ===================================================================',
    "",
    "mode_manual_migration() {",
    '  echo ""',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo -e "${GREEN}  手动迁移指南${NC}"',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo ""',
    '  echo "1. 备份旧系统数据："',
    '  echo "   - 配置文件（.env）"',
    '  echo "   - 上传文件（/uploads）"',
    '  echo "   - 数据库（pg_dump）"',
    '  echo ""',
    '  echo "2. 准备 PostgreSQL 数据库并导入备份"',
    '  echo ""',
    '  echo "3. 将备份的 .env 复制到 ${INSTALL_DIR}/.env"',
    '  echo ""',
    '  echo "4. 修改 .env 中的 DB_HOST 和端口配置"',
    '  echo ""',
    '  echo "5. 将上传文件复制到 ${INSTALL_DIR}/uploads"',
    '  echo ""',
    '  echo "6. 运行：pm2 start ${INSTALL_DIR}/ecosystem.config.js"',
    '  echo ""',
    '  echo "详细步骤参考文档："',
    '  echo "https://github.com/talen8/FlecBlog/tree/main/docs"',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo ""',
    "}",
    "",
    '# ===================================================================',
    '#  安装核心函数',
    '# ===================================================================',
    "",
    "install_binary() {",
    '  local platform="${OS}_${ARCH}"',
    '  local filename="flec-server_${platform}.tar.gz"',
    "",
    "  local mirrors=(",
    '    "https://ghfast.top/https://github.com"',
    '    "https://ghproxy.net/https://github.com"',
    '    "https://github.com"',
    "  )",
    "",
    '  step "下载 Server 二进制"',
    '  mkdir -p "${INSTALL_DIR}"',
    "",
    "  local downloaded=false",
    '  for mirror in "${mirrors[@]}"; do',
    '    [ -z "$mirror" ] && continue',
    '    local url="${mirror}/${REPO}/releases/download/v${VERSION}/${filename}"',
    '    echo "  尝试: $mirror"',
    '    if curl -fSL --connect-timeout 10 --max-time 300 --progress-bar -o "${INSTALL_DIR}/${filename}" "$url"; then',
    "      downloaded=true",
    "      break",
    "    fi",
    '    echo "  失败，尝试下一个..."',
    "  done",
    "",
    '  if [ "$downloaded" != "true" ]; then',
    '    error "所有镜像下载失败"',
    "  fi",
    "",
    "  local THEME_BACKUP=\"\"",
    '  if [ -d "${INSTALL_DIR}/blog/themes" ]; then',
    '    THEME_BACKUP="$(mktemp -d)"',
    '    for theme_dir in "${INSTALL_DIR}/blog/themes"/*/; do',
    '      [ -d "$theme_dir" ] || continue',
    '      theme_name=$(basename "$theme_dir")',
    '      if [ "$theme_name" != "default" ]; then',
    '        cp -r "$theme_dir" "${THEME_BACKUP}/${theme_name}"',
    "      fi",
    "    done",
    "  fi",
    "",
    '  tar xzf "${INSTALL_DIR}/${filename}" -C "${INSTALL_DIR}" --strip-components=1',
    '  rm -f "${INSTALL_DIR}/${filename}"',
    '  rm -rf "${INSTALL_DIR}/blog/.output" "${INSTALL_DIR}/blog/.nuxt" 2>/dev/null || true',
    "",
    '  if [ -n "$THEME_BACKUP" ] && [ -d "$THEME_BACKUP" ]; then',
    '    for theme_dir in "${THEME_BACKUP}"/*/; do',
    '      [ -d "$theme_dir" ] || continue',
    '      theme_name=$(basename "$theme_dir")',
    '      cp -r "$theme_dir" "${INSTALL_DIR}/blog/themes/${theme_name}"',
    "    done",
    '    rm -rf "$THEME_BACKUP"',
    "  fi",
    "",
    '  if [ ! -f "${INSTALL_DIR}/flec-server" ]; then',
    '    error "下载失败，请检查网络或手动下载"',
    "  fi",
    '  chmod +x "${INSTALL_DIR}/flec-server"',
    '  info "Server 二进制已安装"',
    "}",
    "",
    "install_blog() {",
    '  if [ ! -d "${INSTALL_DIR}/blog" ]; then',
    '    error "未找到 Blog 源码"',
    "  fi",
    "",
    '  if [ -d "${INSTALL_DIR}/blog/.output" ]; then',
    '    info "Blog 已构建，跳过"',
    "    return",
    "  fi",
    "",
    '  local has_swap=false',
    '  if swapon --show 2>/dev/null | grep -q .; then',
    '    has_swap=true',
    "  fi",
    '  if [ "$has_swap" != "true" ]; then',
    '    info "创建临时 2GB swap..."',
    "    fallocate -l 2G /tmp/flecblog.swap 2>/dev/null || dd if=/dev/zero of=/tmp/flecblog.swap bs=1M count=2048 2>/dev/null",
    "    chmod 600 /tmp/flecblog.swap",
    "    mkswap /tmp/flecblog.swap 2>/dev/null",
    "    swapon /tmp/flecblog.swap 2>/dev/null || true",
    "  fi",
    "",
    '  step "安装 Blog 依赖"',
    '  cd "${INSTALL_DIR}/blog"',
    "  NODE_ENV=production NUXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=\"--max-old-space-size=3072\" npm ci --registry=https://registry.npmmirror.com",
    "",
    '  step "构建 Blog"',
    "  NUXT_TELEMETRY_DISABLED=1 NUXT_PUBLIC_ACTIVE_THEME=default NODE_OPTIONS=\"--max-old-space-size=3072\" npm run build",
    '  cd "${INSTALL_DIR}"',
    "",
    '  if [ "$has_swap" != "true" ] && [ -f /tmp/flecblog.swap ]; then',
    "    swapoff /tmp/flecblog.swap 2>/dev/null || true",
    "    rm -f /tmp/flecblog.swap",
    "  fi",
    "}",
    "",
    "write_env_and_ecosystem() {",
    '  step "生成配置文件"',
    "",
    '  if [ ! -f "${INSTALL_DIR}/.env" ]; then',
    '    cat > "${INSTALL_DIR}/.env" << EOF',
    "SERVER_PORT=${SERVER_PORT}",
    "SERVER_ALLOW_ORIGINS=*",
    "UPLOAD_DIR=./uploads",
    "DB_HOST=${DB_HOST}",
    "DB_PORT=${DB_PORT}",
    "DB_NAME=${DB_NAME}",
    "DB_USER=${DB_USER}",
    "DB_PASSWORD=${DB_PASSWORD}",
    "JWT_SECRET=${JWT_SECRET}",
    "EOF",
    '    chmod 600 "${INSTALL_DIR}/.env"',
    '    info "已创建 .env"',
    "  fi",
    "",
    '  cat > "${INSTALL_DIR}/ecosystem.config.js" << EOF',
    "module.exports = {",
    "  apps: [",
    "    {",
    '      name: "flec-server",',
    '      script: "./flec-server",',
    '      env_file: "./.env",',
    "      env: {",
    '        NODE_ENV: "production",',
    '        SERVER_PORT: "${SERVER_PORT}",',
    "      },",
    '      max_memory_restart: "512M",',
    "      exp_backoff_restart_delay: 100,",
    "    },",
    "    {",
    '      name: "flec-blog",',
    '      script: "./blog/.output/server/index.mjs",',
    '      env_file: "./.env",',
    "      env: {",
    '        NODE_ENV: "production",',
    '        PORT: "${BLOG_PORT}",',
    '        NUXT_PUBLIC_API_URL: "http://localhost:${SERVER_PORT}/api/v1",',
    "      },",
    '      max_memory_restart: "512M",',
    "      exp_backoff_restart_delay: 100,",
    "    },",
    "  ],",
    "};",
    "EOF",
    '  info "已创建 ecosystem.config.js"',
    "}",
    "",
    "start_services() {",
    '  step "启动服务"',
    '  cd "${INSTALL_DIR}"',
    "  pm2 delete all 2>/dev/null || true",
    "  pm2 start ecosystem.config.js",
    "  pm2 save",
    "  pm2 startup 2>/dev/null || true",
    '  info "服务已启动"',
    "}",
    "",
    "print_install_result() {",
    '  local server_ip=$(get_server_ip)',
    '  echo ""',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo -e "${GREEN}  FlecBlog 安装完成!${NC}"',
    '  echo -e "${GREEN}========================================${NC}"',
    '  echo ""',
    '  echo -e "  安装目录: ${INSTALL_DIR}"',
    '  echo -e "  Server 端口: ${SERVER_PORT}"',
    '  echo -e "  Blog 端口: ${BLOG_PORT}"',
    '  echo ""',
    '  echo -e "  ${YELLOW}访问地址:${NC}"',
    '  echo -e "  Blog: ${GREEN}http://${server_ip}:${BLOG_PORT}/${NC}"',
    '  echo -e "  Admin: ${GREEN}http://${server_ip}:${SERVER_PORT}/admin/${NC}"',
    '  echo ""',
    '  echo -e "  管理服务: ${GREEN}pm2 status${NC}"',
    '  echo ""',
    "}",
    "",
    '# ===================================================================',
    '#  主流程',
    '# ===================================================================',
    "",
    "main() {",
    "  detect_system",
    "  check_deps",
    "  get_latest_version",
    "  show_mode_selection",
    "",
    '  case "$DEPLOY_MODE" in',
    "    fresh)",
    "      mode_fresh_install",
    "      ;;",
    "    docker)",
    "      mode_docker_migration",
    "      ;;",
    "    flecb)",
    "      mode_flecb_migration",
    "      ;;",
    "    manual)",
    "      mode_manual_migration",
    "      ;;",
    "  esac",
    "}",
    "",
    "main",
  ];

  return lines.join("\n");
}
